### ISSUE TITLE
What's the color theme & font you used to create the image in the README?

### ISSUE THREAD

**Issue by pksunkara** [acheronfail/repgrep#103]
Sorry for creating an issue, but was curious.

**Comment by acheronfail** [comment]
Haha no worries, it would be `ayu`. Here's a definition for it: https://github.com/dexpota/kitty-themes/blob/master/themes/ayu.conf

**Comment by acheronfail** [comment]
Oh, and the font is `Iosevka Term`: https://github.com/be5invis/Iosevka
