### ISSUE TITLE
Fix Windows binaries generated on each release

### ISSUE THREAD

**Issue by acheronfail** [acheronfail/repgrep#61]
Right now it doesn't build Windows binaries. 

It should.

**Comment by sergeevabc** [comment]
Err… Could you update the community about the progress, please?

**Comment by cpkio** [comment]
The project seems to be abandoned…

**Comment by dufferzafar** [comment]
@acheronfail Could you please explain what would one have to do to get Windows builds working? Are the libraries that repgrep depends on available on Windows?

**Comment by acheronfail** [comment]
Honestly I don't know. I'm very unfamiliar with development on Windows, and am really wanting someone with some knowledge about building for Windows targets to help out.

Since I don't use Windows myself, this is fairly low on the priority list, but I do hope to get around to it if life permits...

**Comment by cpkio** [comment]
it builds perfectly on windows with `cargo build --release`. that's a CI issue, not code.

**Comment by acheronfail** [comment]
Alright, I ran this on Windows 11 in a VM, and can confirm the issue is in CI.

CI fails when trying to copy `target/x86_64-pc-windows-msvc/release/rgr.exe`.

I replicated what the CI does though (installing `cross` and using that to compile, etc) and in the VM the file `target/x86_64-pc-windows-msvc/release/rgr.exe` exists, so not entirely sure what the issue is here. :thinking:
