### ISSUE TITLE
`repgrep` indicator should read `.ripgreprc` or some other fix

### ISSUE THREAD

**Issue by cpkio** [acheronfail/repgrep#63]
The arrow indicator does not align with selected lines on searches with context switch:
![2021-10-04_08-30-52](https://user-images.githubusercontent.com/1917113/135798942-df779e1b-9350-450a-8212-4f7b24d009bf.gif)

**Comment by acheronfail** [comment]
Just had a quick look at this, and an easy way to reproduce it is:

```bash
# inside this repository
cargo run -- foo ./src/replace.rs -C1
```

When running it this way, you can see the cursor gets out of alignment whenever there's an empty line in the interface.
I'll have to investigate why this happens. :thinking:

**Comment by acheronfail** [comment]
As a temporary workaround, you can use `C-v` when running `rgr` to render whitespace and control character, this fixes it.

In the meantime, I'll try to get a fix out.
