### ISSUE TITLE
failed to persist temporary file path

### ISSUE THREAD

**Issue by muralikodali** [acheronfail/repgrep#65]
replacement fails with following error : 

```
Failed to make all replacements: failed to persist temporary file path: Invalid cross-device link (os error 18)
An error occurred during replacement: Failed to perform all replacements, see log
Logs available at: /tmp/.repgrep
```

no logs are avaiable at /tmp/.repgrep

**Comment by dimon4ezzz** [comment]
same

**Comment by muralikodali** [comment]
My OS is Arch Linux

```
mount | grep 'tmp' 
/dev/disk/by-uuid/3c6182b4-8f62-4c93-aa76-246fbaa495f6 on /tmp type tmpfs (rw,relatime,inode64)
```

**Comment by acheronfail** [comment]
Ah, so your `/tmp` directory is on a separate disk to where you're running `rgr`? I'll see if I can reproduce it on my machine.

**Comment by acheronfail** [comment]
I can't seem to reproduce this, I've even tried installing Arch in a VM with `/tmp` mounted on a separate disk and even with a different filesystem to where `rgr` is running, and it all just works.

Is there any more information about your system you can give me?

**Comment by acheronfail** [comment]
Ahh, thanks for bringing that up change again, I looked into it some more and discovered this in the `temp_file` crate's [documentation](https://docs.rs/tempfile/3.4.0/tempfile/struct.NamedTempFile.html#method.persist):

> Note: Temporary files cannot be persisted across filesystems. Also neither the file contents nor the containing directory are synchronized, so the update may not yet have reached the disk when persist returns.

Now I know where the error is, I'll see if I can perform the replacement atomically in a different way...

**Comment by acheronfail** [comment]
After reading `tempfile`'s documentation and their issue tracker, I think @jwest23's suggestion aligns with how that crate should be used, so I'll go with that.

Thanks for all your input!
