### ISSUE TITLE
Repgrep changes file permissions

### ISSUE THREAD

**Issue by Twix53791** [acheronfail/repgrep#83]
Hello,

I am glad to use repgrep, but I noticed a problem quite annoying : repgrep changes file permissions to rw------- when I use it.
For example, on a script : from rwx-r-xr-x, it becomes rw-------.
On a regular file: from rw-r--r--, it becomes rw-------.
The bug occurs with `rgr` and `sudo rgr`. Quite annoying. For now, I have to wrap rgr into a bash script to restore file permissions... Ugly!
Thanks for any clue!

Repgrep version: 0.12.2, installed through yay.
System: Arch linux.

PS: If I use sudo rgr, additionally of changing the file permissions, it changes its owner to root !

**Comment by acheronfail** [comment]
Thanks for reporting this! I've opened #84 which includes a fix.

**Comment by acheronfail** [comment]
Fixed in 0.12.4
