### ISSUE TITLE
Seeing duplicate characters for replacement 

### ISSUE THREAD

**Issue by ket000** [acheronfail/repgrep#91]
When trying to type replacement each character appears twice. On windows 11 and latest build.

**Comment by acheronfail** [comment]
Can you provide any more information?

- which terminal/console application are you using?
- command prompt / powershell / cygwin / something else?
- which version of repgrep? (if you compiled, which commit)

**Comment by ket000** [comment]
which terminal/console application are you using?
microsoft terminal : Windows Terminal 1.16.10262.0
which version of repgrep? (if you compiled, which commit)
rg -V
ripgrep 13.0.0
rgr -V
repgrep 0.14.1
does it appear twice in both the input prompt and preview, or just one?
in both. See the screenshot. 
does actually performing the replacement input a single character or double?
Double.

cat test.txt
tteesstt22
test2
test3
![rgr_double_07232023](https://github.com/acheronfail/repgrep/assets/16566709/3b68a7c2-b317-459d-bfac-d3b11a9d9368)

**Comment by acheronfail** [comment]
Awesome, I've been able to reproduce this, will look into a fix.

**Comment by ket000** [comment]
I downloaded 0.14.2 and issue is resolved now.
